# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: four_grpc_modes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66our_grpc_modes.proto\"\"\n\x07Request\x12\x17\n\x0frequest_purpose\x18\x01 \x01(\t\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t2\xbc\x01\n\tFourModes\x12\x1f\n\x08UnaryAPI\x12\x08.Request\x1a\t.Response\x12+\n\x12ServerStreamingAPI\x12\x08.Request\x1a\t.Response0\x01\x12+\n\x12\x43lientStreamingAPI\x12\x08.Request\x1a\t.Response(\x01\x12\x34\n\x19\x42iDirectionalStreamingAPI\x12\x08.Request\x1a\t.Response(\x01\x30\x01\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'four_grpc_modes_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'four_grpc_modes_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_FOURMODES = DESCRIPTOR.services_by_name['FourModes']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=25
  _REQUEST._serialized_end=59
  _RESPONSE._serialized_start=61
  _RESPONSE._serialized_end=89
  _FOURMODES._serialized_start=92
  _FOURMODES._serialized_end=280
# @@protoc_insertion_point(module_scope)
